const object = (properties: Record<string, unknown>, required: string[] = []) => ({
  type: "object",
  properties,
  ...(required.length === 0 ? {} : { required }),
  additionalProperties: false,
});
const array = (items: unknown) => ({ type: "array", items });
const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const nullable = (schema: Record<string, unknown>) => ({ anyOf: [schema, { type: "null" }] });

const id = { type: "integer", minimum: 1 };
const slug = { type: "string", pattern: "^[a-z0-9-]+$" };
const dateTime = nullable({ type: "string", format: "date-time" });
const metadata = { type: "object", additionalProperties: true };
const roles = {
  type: "array",
  uniqueItems: true,
  items: {
    type: "string",
    enum: [
      "ROLE_USER",
      "ROLE_ADMIN",
      "ROLE_MAP_NOMINATOR",
      "ROLE_MODERATOR",
      "ROLE_CHECKER",
      "ROLE_VERIFIED",
      "ROLE_VIP",
      "ROLE_PREMIUM",
    ],
  },
};

export const openApiSchemas = {
  Problem: object({
    type: { type: "string", format: "uri" },
    title: { type: "string" },
    status: { type: "integer" },
    detail: { type: "string" },
    code: { type: "string" },
    details: array(object({ path: { type: "string" }, message: { type: "string" } }, ["path", "message"])),
  }, ["type", "title", "status", "detail", "code"]),
  Health: object({
    status: { type: "string", enum: ["ok", "degraded"] },
    service: { type: "string", const: "zwr-api" },
    checks: object({ database: { type: "boolean" }, redis: { type: "boolean" } }, ["database", "redis"]),
  }, ["status", "service", "checks"]),
  OpenApiDocument: object({
    openapi: { type: "string" },
    info: metadata,
    paths: metadata,
    components: metadata,
  }, ["openapi", "info", "paths"]),
  EmptyObject: object({}),
  AuthSignUpRequest: object({
    email: { type: "string", format: "email" },
    password: { type: "string", minLength: 8 },
    name: { type: "string", minLength: 1 },
  }, ["email", "password", "name"]),
  AuthSignInRequest: object({
    email: { type: "string", format: "email" },
    password: { type: "string", minLength: 1 },
  }, ["email", "password"]),
  SendVerificationEmailRequest: object({
    email: { type: "string", format: "email" },
    callbackURL: { type: "string", format: "uri" },
  }, ["email"]),
  RequestPasswordResetRequest: object({
    email: { type: "string", format: "email" },
    redirectTo: { type: "string", format: "uri" },
  }, ["email", "redirectTo"]),
  ResetPasswordRequest: object({
    token: { type: "string", minLength: 1 },
    newPassword: { type: "string", minLength: 8 },
  }, ["token", "newPassword"]),
  ChangePasswordRequest: object({
    currentPassword: { type: "string", minLength: 1 },
    newPassword: { type: "string", minLength: 8 },
    revokeOtherSessions: { type: "boolean" },
  }, ["currentPassword", "newPassword"]),
  AccountActionResponse: metadata,
  AuthResponse: object({
    token: { type: "string" },
    user: ref("User"),
  }),
  SessionResponse: object({
    session: nullable(metadata),
    user: nullable(ref("User")),
  }),
  User: object({
    id: { type: "string" },
    name: { type: "string" },
    email: { type: "string", format: "email" },
    image: nullable({ type: "string", format: "uri" }),
    backgroundImage: nullable({ type: "string" }),
    profileColor: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
    profileGradientColor: nullable({ type: "string", pattern: "^#[0-9a-fA-F]{6}$" }),
    profileGradientAngle: { type: "integer", minimum: 0, maximum: 360 },
    countryCode: nullable({ type: "string", pattern: "^[A-Z]{2}$" }),
    countryChangedAt: nullable(dateTime),
    roles,
    performancePoints: { type: "number" },
  }, ["id", "name"]),
  UserSummary: object({
    id: { type: "string" },
    name: { type: "string" },
    image: nullable({ type: "string", format: "uri" }),
    backgroundImage: nullable({ type: "string" }),
    profileColor: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
    profileGradientColor: nullable({ type: "string", pattern: "^#[0-9a-fA-F]{6}$" }),
    profileGradientAngle: { type: "integer", minimum: 0, maximum: 360 },
    countryCode: nullable({ type: "string", pattern: "^[A-Z]{2}$" }),
    countryChangedAt: nullable(dateTime),
  }, ["id", "name", "image"]),
  UserCollection: object({
    search: nullable({ type: "string" }),
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    totalEntries: { type: "integer", minimum: 0 },
    totalPages: { type: "integer", minimum: 0 },
    hasMore: { type: "boolean" },
    entries: array(ref("PerformanceUser")),
  }, ["search", "page", "pageSize", "hasMore", "entries"]),
  PlatformStats: object({
    playerCount: { type: "integer", minimum: 0 },
    submissionCount: { type: "integer", minimum: 0 },
    gameCount: { type: "integer", minimum: 0 },
    mapCount: { type: "integer", minimum: 0 },
    categoryCount: { type: "integer", minimum: 0 },
  }, ["playerCount", "submissionCount", "gameCount", "mapCount", "categoryCount"]),
  UserRecords: object({
    user: ref("PerformanceUser"),
    globalRank: { type: "integer", minimum: 1 },
    countryRank: nullable({ type: "integer", minimum: 1 }),
    countryPlayerCount: nullable({ type: "integer", minimum: 1 }),
    recordCount: { type: "integer", minimum: 0 },
    averageRecordPoints: { type: "number", minimum: 0 },
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    hasMore: { type: "boolean" },
    pinnedSubmissionIds: array({ type: "integer", minimum: 1 }),
    pinnedEntries: array(metadata),
    worldRecordEntries: array(metadata),
    entries: array(metadata),
  }, [
    "user",
    "globalRank",
    "countryRank",
    "countryPlayerCount",
    "recordCount",
    "averageRecordPoints",
    "page",
    "pageSize",
    "hasMore",
    "pinnedSubmissionIds",
    "pinnedEntries",
    "worldRecordEntries",
    "entries",
  ]),
  UserHistory: object({
    user: ref("PerformanceUser"),
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 25 },
    hasMore: { type: "boolean" },
    entries: array(metadata),
  }, ["user", "page", "pageSize", "hasMore", "entries"]),
  PerformanceHistory: object({
    userId: { type: "string" },
    currentPoints: { type: "number" },
    entries: array(object({
      id,
      points: { type: "number" },
      delta: { type: "number" },
      source: { type: "string", enum: ["baseline", "submission", "daily", "formula_change"] },
      sourceSubmissionId: nullable(id),
      formulaVersion: { type: "integer", minimum: 1 },
      recordedAt: { type: "string", format: "date-time" },
    }, ["id", "points", "delta", "source", "sourceSubmissionId", "formulaVersion", "recordedAt"])),
  }, ["userId", "currentPoints", "entries"]),
  UserScopedRanks: object({
    userId: { type: "string" },
    games: array(metadata),
    categories: array(metadata),
  }, ["userId", "games", "categories"]),
  UserSocialContext: object({
    userId: { type: "string" },
    clan: nullable(metadata),
    frequentTeams: array(metadata),
  }, ["userId", "clan", "frequentTeams"]),
  PerformanceUser: object({
    id: { type: "string" },
    name: { type: "string" },
    image: nullable({ type: "string", format: "uri" }),
    backgroundImage: nullable({ type: "string" }),
    profileColor: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
    profileGradientColor: nullable({ type: "string", pattern: "^#[0-9a-fA-F]{6}$" }),
    profileGradientAngle: { type: "integer", minimum: 0, maximum: 360 },
    performancePoints: { type: "number" },
    isClaimable: { type: "boolean" },
  }, ["id", "name", "image", "performancePoints"]),
  RosterSummary: object({
    competitorKey: { type: "string", pattern: "^team:" },
    playerCount: { type: "integer", enum: [2, 3, 4] },
    members: array(ref("UserSummary")),
    performancePoints: { type: "number" },
    recordCount: { type: "integer", minimum: 1 },
    firstPlaces: { type: "integer", minimum: 0 },
    podiums: { type: "integer", minimum: 0 },
    lastVerifiedAt: dateTime,
  }, [
    "competitorKey",
    "playerCount",
    "members",
    "performancePoints",
    "recordCount",
    "firstPlaces",
    "podiums",
    "lastVerifiedAt",
  ]),
  RosterLeaderboard: object({
    filters: object({
      playerCount: { type: "integer", enum: [2, 3, 4] },
      categories: array({ type: "string" }),
      game: nullable({ type: "string" }),
      mapsStatus: nullable({ type: "string", enum: ["official", "community"] }),
    }, ["playerCount", "categories"]),
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    hasMore: { type: "boolean" },
    entries: array({
      allOf: [ref("RosterSummary"), object({ rank: { type: "integer", minimum: 1 } }, ["rank"])],
    }),
  }, ["filters", "page", "pageSize", "hasMore", "entries"]),
  RosterRecord: object({
    submissionId: id,
    competitorKey: { type: "string", pattern: "^team:" },
    playerCount: { type: "integer", enum: [2, 3, 4] },
    scoreValue: { type: "integer" },
    runDurationMs: nullable({ type: "integer" }),
    proofLevel: { type: "string" },
    proofUrl: nullable({ type: "string", format: "uri" }),
    verifiedAt: dateTime,
    points: { type: "number" },
    isWorldRecord: { type: "boolean" },
    categoryAssignmentId: nullable(id),
    game: ref("GameSummary"),
    map: ref("MapSummary"),
    category: ref("CategorySummary"),
  }, [
    "submissionId",
    "competitorKey",
    "playerCount",
    "scoreValue",
    "proofLevel",
    "points",
    "isWorldRecord",
    "game",
    "map",
    "category",
  ]),
  RosterRecords: object({
    competitorKey: { type: "string", pattern: "^team:" },
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    hasMore: { type: "boolean" },
    entries: array(ref("RosterRecord")),
  }, ["competitorKey", "page", "pageSize", "hasMore", "entries"]),
  FollowCreateRequest: object({
    targetType: {
      type: "string",
      enum: ["user", "game", "map", "category_assignment", "map_category", "team"],
    },
    targetId: { type: "string", minLength: 1, maxLength: 300 },
  }, ["targetType", "targetId"]),
  Follow: object({
    id,
    followerUserId: { type: "string" },
    targetType: {
      type: "string",
      enum: ["user", "game", "map", "category_assignment", "map_category", "team"],
    },
    targetId: { type: "string" },
    createdAt: { type: "string", format: "date-time" },
  }, ["id", "followerUserId", "targetType", "targetId", "createdAt"]),
  FollowList: array(ref("Follow")),
  GoalCreateRequest: object({
    title: { type: "string", minLength: 1, maxLength: 120 },
    metric: {
      type: "string",
      enum: ["performance_points", "verified_submissions", "round", "time", "rank"],
    },
    targetValue: { type: "number", exclusiveMinimum: 0 },
    dueAt: nullable({ type: "string", format: "date-time" }),
    gameId: id,
    mapId: id,
    categoryAssignmentId: id,
    playerCount: { type: "integer", minimum: 1, maximum: 4 },
  }, ["title", "metric", "targetValue"]),
  GoalUpdateRequest: object({ status: { type: "string", enum: ["active", "abandoned"] } }, ["status"]),
  Goal: object({
    id,
    userId: { type: "string" },
    title: { type: "string" },
    metric: {
      type: "string",
      enum: ["performance_points", "verified_submissions", "round", "time", "rank"],
    },
    targetValue: { type: "number" },
    progress: { type: "number" },
    status: { type: "string", enum: ["active", "completed", "abandoned"] },
    dueAt: dateTime,
    direction: { type: "string", enum: ["higher_is_better", "lower_is_better"] },
    gameId: nullable(id),
    mapId: nullable(id),
    categoryAssignmentId: nullable(id),
    playerCount: nullable({ type: "integer", minimum: 1, maximum: 4 }),
    board: nullable(metadata),
  }, ["id", "userId", "title", "metric", "targetValue", "progress", "status", "direction"]),
  GoalList: array(ref("Goal")),
  AchievementCreateRequest: object({
    slug,
    name: { type: "string" },
    description: { type: "string" },
    metric: {
      type: "string",
      enum: [
        "performance_points",
        "verified_submissions",
        "world_records",
        "games_played",
        "team_records",
        "record_points",
        "classic_high_round",
        "bo3_high_round",
        "waw_high_round",
        "speedrun_30",
        "speedrun_50",
        "speedrun_100",
        "other_speedrun_30",
        "other_speedrun_50",
        "other_speedrun_100",
        "no_power_round",
        "maps_played",
        "team_best_rank",
        "map_top15_categories",
        "map_all_categories_top15",
        "world_records_2p",
        "world_records_3p",
        "world_records_4p",
        "team_formats_played",
        "categories_played",
        "game_high_round_top15_complete",
        "game_ee_top20_records",
        "game_all_ee_top20",
        "community_records",
        "community_best_rank",
        "bo3_gum_trio_best_rank",
        "back_from_the_dead",
        "podium_records",
        "jack_of_all_trades_top3",
        "game_specialist_records",
        "map_domination_best_rank",
        "dynamic_duo_records",
        "dynamic_duo_world_records",
        "distinct_top3_duo_partners",
        "distinct_top1_duo_partners",
        "duo_self_snipe",
        "self_wr_improvement",
        "wr_weekend",
        "wr_games",
        "longest_wr_reign_days",
        "record_breaker_days",
        "format_sweep_best_rank",
        "speedrun_ladder_best_rank",
        "no_crutches_best_rank",
        "clean_extraction_best_rank",
        "double_agent_best_rank",
        "restricted_arsenal_best_rank",
        "hardcore_credentials_best_rank",
        "first_room_official_round",
        "flawless_official_round",
        "extinction_protocol_best_rank",
        "endurance_best_rank",
        "bo3_reset_maps",
      ],
    },
    threshold: { type: "number", exclusiveMinimum: 0 },
    direction: { type: "string", enum: ["higher_is_better", "lower_is_better"] },
    category: { type: "string" },
    series: slug,
    tier: { type: "integer", minimum: 1 },
    points: { type: "integer", minimum: 1 },
  }, ["slug", "name", "description", "metric", "threshold"]),
  Achievement: object({
    id,
    slug,
    name: { type: "string" },
    description: { type: "string" },
    metric: { type: "string" },
    threshold: { type: "number" },
    direction: { type: "string", enum: ["higher_is_better", "lower_is_better"] },
    category: { type: "string" },
    series: { type: "string" },
    tier: { type: "integer" },
    points: { type: "integer" },
    achievementPoints: { type: "integer" },
    active: { type: "boolean" },
    progress: nullable({ type: "number" }),
    unlockedAt: dateTime,
  }, [
    "id",
    "slug",
    "name",
    "description",
    "metric",
    "threshold",
    "direction",
    "category",
    "series",
    "tier",
    "points",
    "achievementPoints",
    "active",
    "progress",
    "unlockedAt",
  ]),
  AchievementList: array(ref("Achievement")),
  AchievementRecalculation: object({
    playersProcessed: { type: "integer" },
    newUnlocks: { type: "integer" },
    totalUnlocks: { type: "integer" },
  }, ["playersProcessed", "newUnlocks", "totalUnlocks"]),
  ChallengeCreateRequest: object({
    slug,
    name: { type: "string" },
    description: { type: "string" },
    metric: { type: "string", enum: ["performance_points", "verified_submissions"] },
    targetValue: { type: "number", exclusiveMinimum: 0 },
    startsAt: { type: "string", format: "date-time" },
    endsAt: { type: "string", format: "date-time" },
  }, ["slug", "name", "description", "metric", "targetValue", "startsAt", "endsAt"]),
  Challenge: object({
    id,
    slug,
    name: { type: "string" },
    description: { type: "string" },
    metric: { type: "string", enum: ["performance_points", "verified_submissions"] },
    targetValue: { type: "number" },
    startsAt: { type: "string", format: "date-time" },
    endsAt: { type: "string", format: "date-time" },
    active: { type: "boolean" },
    progress: nullable({ type: "number" }),
  }, [
    "id",
    "slug",
    "name",
    "description",
    "metric",
    "targetValue",
    "startsAt",
    "endsAt",
    "active",
    "progress",
  ]),
  ChallengeList: array(ref("Challenge")),
  ModerationOverview: object({
    submissions: metadata,
    profileClaims: metadata,
    oldestPendingSubmission: nullable(object({ id, submittedAt: { type: "string", format: "date-time" } }, [
      "id",
      "submittedAt",
    ])),
  }, ["submissions", "profileClaims", "oldestPendingSubmission"]),
  SocialEvent: object({
    id,
    outboxEventId: id,
    type: { type: "string" },
    actorUserId: nullable({ type: "string" }),
    payload: metadata,
    createdAt: { type: "string", format: "date-time" },
  }, ["id", "outboxEventId", "type", "actorUserId", "payload", "createdAt"]),
  Notification: object({
    id,
    recipientUserId: { type: "string" },
    outboxEventId: id,
    type: { type: "string" },
    actorUserId: nullable({ type: "string" }),
    payload: metadata,
    readAt: dateTime,
    createdAt: { type: "string", format: "date-time" },
  }, [
    "id",
    "recipientUserId",
    "outboxEventId",
    "type",
    "actorUserId",
    "payload",
    "readAt",
    "createdAt",
  ]),
  FeedPage: object({
    entries: array(ref("SocialEvent")),
    nextCursor: nullable(id),
    hasMore: { type: "boolean" },
  }, ["entries", "nextCursor", "hasMore"]),
  NotificationPage: object({
    entries: array(ref("Notification")),
    nextCursor: nullable(id),
    hasMore: { type: "boolean" },
  }, ["entries", "nextCursor", "hasMore"]),
  NotificationCount: object({ count: { type: "integer", minimum: 0 } }, ["count"]),
  NotificationReadAll: object({ updated: { type: "integer", minimum: 0 } }, ["updated"]),
  RemovalResult: object({ removed: { type: "boolean", const: true } }, ["removed"]),
  PersonalRunCreateRequest: object({
    gameId: id,
    mapId: id,
    categoryAssignmentId: id,
    playerCount: { type: "integer", const: 1 },
    scoreValue: { type: "integer", minimum: 1 },
    runDurationMs: nullable({ type: "integer", minimum: 1 }),
    proofLevel: nullable({
      type: "string",
      enum: ["manual_video", "client_recorded", "client_recorded_with_inputs", "verified_client_package"],
    }),
    proofUrl: nullable({ type: "string", format: "uri" }),
    visibility: { type: "string", enum: ["private", "followers", "public"] },
    notes: nullable({ type: "string", maxLength: 5_000 }),
    metadata,
  }, ["gameId", "mapId", "categoryAssignmentId", "scoreValue"]),
  PersonalRunUpdateRequest: object({
    scoreValue: { type: "integer", minimum: 1 },
    runDurationMs: nullable({ type: "integer", minimum: 1 }),
    proofLevel: nullable({
      type: "string",
      enum: ["manual_video", "client_recorded", "client_recorded_with_inputs", "verified_client_package"],
    }),
    proofUrl: nullable({ type: "string", format: "uri" }),
    visibility: { type: "string", enum: ["private", "followers", "public"] },
    notes: nullable({ type: "string", maxLength: 5_000 }),
    metadata,
  }),
  PersonalRun: object({
    id,
    userId: { type: "string" },
    categoryAssignmentId: id,
    playerCount: { type: "integer", const: 1 },
    scoreValue: { type: "integer", minimum: 1 },
    runDurationMs: nullable({ type: "integer", minimum: 1 }),
    proofLevel: nullable({ type: "string" }),
    proofUrl: nullable({ type: "string", format: "uri" }),
    visibility: { type: "string", enum: ["private", "followers", "public"] },
    notes: nullable({ type: "string" }),
    metadata,
    promotedSubmissionId: nullable(id),
    promotedAt: dateTime,
    createdAt: { type: "string", format: "date-time" },
    updatedAt: { type: "string", format: "date-time" },
    game: ref("GameSummary"),
    map: ref("MapSummary"),
    category: object({
      id,
      slug,
      name: { type: "string" },
      scoreType: { type: "string" },
      rankingDirection: { type: "string", enum: ["higher_is_better", "lower_is_better"] },
    }, ["id", "slug", "name", "scoreType", "rankingDirection"]),
  }, [
    "id",
    "userId",
    "categoryAssignmentId",
    "playerCount",
    "scoreValue",
    "runDurationMs",
    "proofLevel",
    "proofUrl",
    "visibility",
    "notes",
    "metadata",
    "promotedSubmissionId",
    "promotedAt",
    "createdAt",
    "updatedAt",
    "game",
    "map",
    "category",
  ]),
  PersonalRunPage: object({
    entries: array(ref("PersonalRun")),
    nextCursor: nullable(id),
    hasMore: { type: "boolean" },
  }, ["entries", "nextCursor", "hasMore"]),
  PersonalBestList: object({ entries: array(ref("PersonalRun")) }, ["entries"]),
  PersonalRunPromotion: object({
    personalRun: ref("PersonalRun"),
    submission: ref("Submission"),
  }, ["personalRun", "submission"]),
  ClientVersionCreateRequest: object({
    clientName: { type: "string", pattern: "^[a-zA-Z0-9._-]{1,100}$" },
    version: { type: "string", pattern: "^[a-zA-Z0-9._-]{1,100}$" },
    protocolVersion: { type: "integer", const: 1 },
    releaseNotes: nullable({ type: "string" }),
  }, ["clientName", "version", "protocolVersion"]),
  ClientVersionUpdateRequest: object({
    status: { type: "string", enum: ["allowed", "revoked"] },
  }, ["status"]),
  ClientVersion: object({
    id,
    clientName: { type: "string" },
    version: { type: "string" },
    protocolVersion: { type: "integer", const: 1 },
    status: { type: "string", enum: ["allowed", "revoked"] },
    releaseNotes: nullable({ type: "string" }),
    createdAt: { type: "string", format: "date-time" },
    updatedAt: { type: "string", format: "date-time" },
  }, ["id", "clientName", "version", "protocolVersion", "status", "releaseNotes", "createdAt", "updatedAt"]),
  ClientVersionList: object({ entries: array(ref("ClientVersion")) }, ["entries"]),
  ClientInstallationCreateRequest: object({
    name: { type: "string", minLength: 1, maxLength: 100 },
    publicKeySpki: { type: "string", description: "Base64-encoded Ed25519 SubjectPublicKeyInfo" },
  }, ["name", "publicKeySpki"]),
  ClientInstallation: object({
    id: { type: "string", format: "uuid" },
    name: { type: "string" },
    revokedAt: dateTime,
    lastUsedAt: dateTime,
    createdAt: { type: "string", format: "date-time" },
  }, ["id", "name", "revokedAt", "lastUsedAt", "createdAt"]),
  ClientInstallationList: object({ entries: array(ref("ClientInstallation")) }, ["entries"]),
  ClientInstallationRevocation: object({
    id: { type: "string", format: "uuid" },
    revokedAt: { type: "string", format: "date-time" },
  }, ["id", "revokedAt"]),
  ClientRunStartRequest: object({
    runId: { type: "string", format: "uuid" },
    runToken: { type: "string", minLength: 43, maxLength: 43 },
    installationId: { type: "string", format: "uuid" },
    clientName: { type: "string" },
    clientVersion: { type: "string" },
    protocolVersion: { type: "integer", const: 1 },
    gameId: id,
    mapId: id,
    platform: nullable({ type: "string" }),
    gameVersion: nullable({ type: "string" }),
    mapVersion: nullable({ type: "string" }),
    modId: nullable(id),
    modVersion: nullable({ type: "string" }),
    participantUserIds: { type: "array", minItems: 1, maxItems: 4, items: { type: "string" } },
    signature: { type: "string", description: "Base64 Ed25519 signature" },
  }, [
    "runId",
    "runToken",
    "installationId",
    "clientName",
    "clientVersion",
    "protocolVersion",
    "gameId",
    "mapId",
    "signature",
  ]),
  ClientRunHeartbeatRequest: object({
    runToken: { type: "string", minLength: 43, maxLength: 43 },
    sequence: { type: "integer", minimum: 1 },
    gameElapsedMs: { type: "integer", minimum: 0 },
    round: nullable({ type: "integer", minimum: 1 }),
    observedAt: { type: "string", format: "date-time" },
    signature: { type: "string" },
  }, ["runToken", "sequence", "gameElapsedMs", "observedAt", "signature"]),
  ClientRunChunkRequest: object({
    runToken: { type: "string", minLength: 43, maxLength: 43 },
    sequence: { type: "integer", minimum: 1 },
    startElapsedMs: { type: "integer", minimum: 0 },
    endElapsedMs: { type: "integer", minimum: 1 },
    previousChunkSha256: nullable({ type: "string", pattern: "^[a-fA-F0-9]{64}$" }),
    compression: { type: "string", const: "gzip" },
    payloadFormat: { type: "string", const: "events-v1" },
    compressedSha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" },
    uncompressedSha256: { type: "string", pattern: "^[a-fA-F0-9]{64}$" },
    compressedDataBase64: { type: "string", contentEncoding: "base64" },
    signature: { type: "string" },
  }, [
    "runToken",
    "sequence",
    "startElapsedMs",
    "endElapsedMs",
    "compression",
    "payloadFormat",
    "compressedSha256",
    "uncompressedSha256",
    "compressedDataBase64",
    "signature",
  ]),
  ClientRunRecoveryRequest: object({ signature: { type: "string" } }, ["signature"]),
  ClientRunAbandonRequest: object({
    runToken: { type: "string", minLength: 43, maxLength: 43 },
    signature: { type: "string" },
  }, ["runToken", "signature"]),
  ClientRunFinalizeRequest: object({
    runToken: { type: "string", minLength: 43, maxLength: 43 },
    interrupted: { type: "boolean" },
    finalState: object({
      gameElapsedMs: { type: "integer", minimum: 0 },
      round: nullable({ type: "integer", minimum: 1 }),
      endedAt: { type: "string", format: "date-time" },
    }, ["gameElapsedMs", "endedAt"]),
    entries: { type: "array", minItems: 1, maxItems: 5, items: ref("SubmissionGroupEntryRequest") },
    proofUrl: nullable({ type: "string", format: "uri" }),
    metadata,
    signature: { type: "string" },
  }, ["runToken", "interrupted", "finalState", "entries", "signature"]),
  ClientRun: object({
    id: { type: "string", format: "uuid" },
    userId: { type: "string" },
    installationId: { type: "string", format: "uuid" },
    clientVersionId: id,
    gameId: id,
    mapId: id,
    platform: nullable({ type: "string" }),
    gameVersion: nullable({ type: "string" }),
    mapVersion: nullable({ type: "string" }),
    modId: nullable(id),
    modVersion: nullable({ type: "string" }),
    participantUserIds: array({ type: "string" }),
    startPayloadSha256: { type: "string", pattern: "^[a-f0-9]{64}$" },
    status: { type: "string", enum: ["active", "finalizing", "finalized", "abandoned"] },
    latestHeartbeatSequence: { type: "integer", minimum: 0 },
    latestGameElapsedMs: { type: "integer", minimum: 0 },
    latestRound: nullable({ type: "integer", minimum: 1 }),
    lastHeartbeatAt: dateTime,
    heartbeatGapCount: { type: "integer", minimum: 0 },
    maxHeartbeatGapMs: { type: "integer", minimum: 0 },
    latestChunkSequence: { type: "integer", minimum: 0 },
    latestChunkEndElapsedMs: { type: "integer", minimum: 0 },
    chunkChainHeadSha256: nullable({ type: "string", pattern: "^[a-f0-9]{64}$" }),
    finalizationSha256: nullable({ type: "string", pattern: "^[a-f0-9]{64}$" }),
    finalizationIssues: array({ type: "string" }),
    submissionGroupId: nullable({ type: "string", format: "uuid" }),
    finalizedAt: dateTime,
    abandonedAt: dateTime,
    createdAt: { type: "string", format: "date-time" },
    updatedAt: { type: "string", format: "date-time" },
  }, [
    "id",
    "userId",
    "installationId",
    "clientVersionId",
    "gameId",
    "mapId",
    "participantUserIds",
    "startPayloadSha256",
    "status",
    "latestHeartbeatSequence",
    "latestGameElapsedMs",
    "latestRound",
    "lastHeartbeatAt",
    "heartbeatGapCount",
    "maxHeartbeatGapMs",
    "latestChunkSequence",
    "latestChunkEndElapsedMs",
    "chunkChainHeadSha256",
    "finalizationSha256",
    "finalizationIssues",
    "submissionGroupId",
    "finalizedAt",
    "abandonedAt",
    "createdAt",
    "updatedAt",
  ]),
  ClientRunChunk: object({
    id,
    runId: { type: "string", format: "uuid" },
    sequence: { type: "integer", minimum: 1 },
    startElapsedMs: { type: "integer", minimum: 0 },
    endElapsedMs: { type: "integer", minimum: 1 },
    previousChunkSha256: nullable({ type: "string" }),
    compressedSha256: { type: "string" },
    uncompressedSha256: { type: "string" },
    compression: { type: "string", const: "gzip" },
    payloadFormat: { type: "string", const: "events-v1" },
    uncompressedBytes: { type: "integer", minimum: 1 },
    eventCount: { type: "integer", minimum: 0 },
    createdAt: { type: "string", format: "date-time" },
  }, [
    "id",
    "runId",
    "sequence",
    "startElapsedMs",
    "endElapsedMs",
    "previousChunkSha256",
    "compressedSha256",
    "uncompressedSha256",
    "compression",
    "payloadFormat",
    "uncompressedBytes",
    "eventCount",
    "createdAt",
  ]),
  ClientRunMutationResult: object({
    run: ref("ClientRun"),
    idempotentReplay: { type: "boolean" },
  }, ["run", "idempotentReplay"]),
  ClientRunChunkResult: object({
    run: ref("ClientRun"),
    chunk: ref("ClientRunChunk"),
    idempotentReplay: { type: "boolean" },
  }, ["run", "chunk", "idempotentReplay"]),
  ClientRunRecovery: object({
    run: ref("ClientRun"),
    runToken: { type: "string", minLength: 43, maxLength: 43 },
  }, ["run", "runToken"]),
  ClientRunFinalization: object({
    run: ref("ClientRun"),
    submissions: array(ref("Submission")),
    idempotentReplay: { type: "boolean" },
  }, ["run", "submissions", "idempotentReplay"]),
  ClientRunDetail: object({
    run: ref("ClientRun"),
    chunks: array(ref("ClientRunChunk")),
    submissions: array(ref("Submission")),
  }, ["run", "chunks", "submissions"]),
  ProfileClaimCreateRequest: object({
    profileUserId: { type: "string", minLength: 1 },
    proofUrl: { type: "string", format: "uri" },
    message: { type: "string", maxLength: 2_000 },
  }, ["profileUserId", "proofUrl"]),
  ProfileClaimReviewRequest: object({
    status: { type: "string", enum: ["approved", "rejected"] },
    reviewNote: { type: "string", maxLength: 2_000 },
  }, ["status"]),
  ProfileClaim: object({
    id,
    claimantUserId: { type: "string" },
    profileUserId: nullable({ type: "string" }),
    profileExternalId: { type: "string" },
    proofUrl: { type: "string", format: "uri" },
    message: nullable({ type: "string" }),
    status: { type: "string", enum: ["pending", "approved", "rejected"] },
    reviewedBy: nullable({ type: "string" }),
    reviewNote: nullable({ type: "string" }),
    createdAt: { type: "string", format: "date-time" },
    reviewedAt: dateTime,
  }, [
    "id",
    "claimantUserId",
    "profileUserId",
    "profileExternalId",
    "proofUrl",
    "message",
    "status",
    "reviewedBy",
    "reviewNote",
    "createdAt",
    "reviewedAt",
  ]),
  ProfileClaimList: array(ref("ProfileClaim")),
  ProfileUpdateRequest: object({
    name: { type: "string", minLength: 1, maxLength: 80 },
    countryCode: nullable({ type: "string", pattern: "^[A-Za-z]{2}$" }),
  }),
  ProfileUpdateResponse: object({
    id: { type: "string" },
    name: { type: "string" },
    image: nullable({ type: "string", format: "uri" }),
    countryCode: nullable({ type: "string", pattern: "^[A-Z]{2}$" }),
    countryChangedAt: nullable(dateTime),
  }, ["id", "name", "image"]),
  AccountDeleteRequest: object({
    confirmation: { type: "string", const: "DELETE" },
    password: { type: "string", minLength: 1 },
  }, ["confirmation", "password"]),
  AccountDeleteResponse: object({ deleted: { type: "boolean", const: true } }, ["deleted"]),
  UserRoleUpdateRequest: object({ roles }, ["roles"]),
  UserRoles: object({
    id: { type: "string" },
    name: { type: "string" },
    roles,
  }, ["id", "name", "roles"]),
  BadgeCreateRequest: object({
    slug: { type: "string", pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$" },
    name: { type: "string", minLength: 1, maxLength: 60 },
    description: { type: "string", maxLength: 240 },
    color: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
    icon: nullable({ type: "string", maxLength: 40 }),
  }, ["slug", "name"]),
  Badge: object({
    id,
    slug,
    name: { type: "string" },
    description: { type: "string" },
    color: { type: "string", pattern: "^#[0-9a-fA-F]{6}$" },
    icon: nullable({ type: "string" }),
    system: { type: "boolean" },
    awardedAt: { type: "string", format: "date-time" },
  }, ["id", "slug", "name", "description", "color", "icon", "system"]),
  BadgeList: array(ref("Badge")),
  ClanCreateRequest: object({
    name: { type: "string", minLength: 2, maxLength: 80 },
  }, ["name"]),
  ClanInviteRequest: object({ userId: { type: "string", minLength: 1 } }, ["userId"]),
  ClanInvitationDecisionRequest: object({
    status: { type: "string", enum: ["accepted", "rejected"] },
  }, ["status"]),
  ClanMemberRoleRequest: object({
    role: { type: "string", enum: ["admin", "member"] },
  }, ["role"]),
  ClanOwnershipTransferRequest: object({ userId: { type: "string", minLength: 1 } }, ["userId"]),
  ClanPreferencesRequest: object({ autoAcceptClanRuns: { type: "boolean" } }, ["autoAcceptClanRuns"]),
  ClanPreferences: object({ autoAcceptClanRuns: { type: "boolean" } }, ["autoAcceptClanRuns"]),
  ClanMembership: object({
    id,
    clanId: id,
    userId: { type: "string" },
    role: { type: "string", enum: ["owner", "admin", "member"] },
    joinedAt: { type: "string", format: "date-time" },
  }, ["id", "clanId", "userId", "role", "joinedAt"]),
  ClanMember: object({
    id,
    role: { type: "string", enum: ["owner", "admin", "member"] },
    joinedAt: { type: "string", format: "date-time" },
    user: ref("UserSummary"),
  }, ["id", "role", "joinedAt", "user"]),
  Clan: object({
    id,
    slug,
    name: { type: "string" },
    createdBy: { type: "string" },
    createdAt: { type: "string", format: "date-time" },
    updatedAt: { type: "string", format: "date-time" },
    members: array(ref("ClanMember")),
  }, ["id", "slug", "name", "createdBy", "createdAt", "updatedAt", "members"]),
  OwnClan: object({ clan: nullable(ref("Clan")) }, ["clan"]),
  ClanInvitation: object({
    id,
    clanId: id,
    inviteeUserId: { type: "string" },
    invitedBy: nullable({ type: "string" }),
    status: { type: "string", enum: ["pending", "accepted", "rejected", "revoked", "expired"] },
    expiresAt: { type: "string", format: "date-time" },
    respondedAt: dateTime,
    createdAt: { type: "string", format: "date-time" },
  }, ["id", "clanId", "inviteeUserId", "status", "expiresAt", "createdAt"]),
  ClanInvitationList: array(object({
    invitation: ref("ClanInvitation"),
    clan: object({ id, slug, name: { type: "string" } }, ["id", "slug", "name"]),
    inviter: nullable(object({ id: { type: "string" }, name: { type: "string" } }, ["id", "name"])),
  }, ["invitation", "clan", "inviter"])),
  ClanManagedInvitationList: array(object({
    invitation: ref("ClanInvitation"),
    invitee: ref("UserSummary"),
  }, ["invitation", "invitee"])),
  ClanInvitationDecision: object({
    invitation: ref("ClanInvitation"),
    clan: nullable(ref("Clan")),
  }, ["invitation", "clan"]),
  ClanMemberRemoval: object({ removed: { type: "boolean", const: true } }, ["removed"]),
  ClanAuditEvent: object({
    id,
    clanId: id,
    actorUserId: nullable({ type: "string" }),
    targetUserId: nullable({ type: "string" }),
    type: { type: "string" },
    metadata,
    createdAt: { type: "string", format: "date-time" },
  }, ["id", "clanId", "type", "metadata", "createdAt"]),
  ClanAuditEventList: array(ref("ClanAuditEvent")),
  Game: object({
    id,
    slug,
    name: { type: "string" },
    shortName: { type: "string" },
    releaseYear: nullable({ type: "integer", minimum: 1900 }),
    gameType: { type: "string", enum: ["zombies", "non_zombies"] },
    studio: { type: "string" },
    isActive: { type: "boolean" },
    metadata,
    createdAt: { type: "string", format: "date-time" },
  }, ["id", "slug", "name", "shortName", "gameType", "studio", "isActive", "metadata", "createdAt"]),
  GameCreateRequest: object({
    slug,
    name: { type: "string", minLength: 1 },
    shortName: { type: "string", minLength: 1 },
    releaseYear: { type: "integer", minimum: 1900 },
    gameType: { type: "string", enum: ["zombies", "non_zombies"] },
    studio: { type: "string", minLength: 1 },
    metadata,
  }, ["slug", "name", "shortName"]),
  GameSummary: object({
    id,
    slug,
    name: { type: "string" },
  }, ["id", "slug", "name"]),
  GameUpdateRequest: object({
    name: { type: "string", minLength: 1 },
    shortName: { type: "string", minLength: 1 },
    releaseYear: nullable({ type: "integer", minimum: 1900 }),
    gameType: { type: "string", enum: ["zombies", "non_zombies"] },
    studio: { type: "string", minLength: 1 },
    isActive: { type: "boolean" },
    metadata,
  }),
  PaginatedGames: object({
    search: nullable({ type: "string" }),
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    hasMore: { type: "boolean" },
    entries: array(ref("Game")),
  }, ["search", "page", "pageSize", "hasMore", "entries"]),
  MapSource: object({
    id,
    mapId: id,
    source: { type: "string", enum: ["steam", "ugx", "manual", "other"] },
    sourceUrl: { type: "string", format: "uri" },
    externalId: nullable({ type: "string" }),
    metadata,
  }, ["source", "sourceUrl"]),
  MapSourceRequest: object({
    source: { type: "string", enum: ["steam", "ugx", "manual", "other"] },
    sourceUrl: { type: "string", format: "uri" },
    externalId: nullable({ type: "string" }),
    metadata,
  }, ["source", "sourceUrl"]),
  Map: object({
    id,
    gameId: id,
    slug,
    name: { type: "string" },
    type: { type: "string", enum: ["official", "custom", "uem"] },
    status: { type: "string", enum: ["draft", "published", "archived"] },
    thumbnailUrl: nullable({ type: "string", format: "uri" }),
    description: nullable({ type: "string" }),
    authors: array({ type: "string" }),
    metadata,
    createdAt: { type: "string", format: "date-time" },
    sources: array(ref("MapSource")),
  }, ["id", "gameId", "slug", "name", "type", "status", "authors", "metadata", "createdAt"]),
  MapCreateRequest: object({
    gameId: id,
    slug,
    name: { type: "string", minLength: 1 },
    type: { type: "string", enum: ["official", "custom", "uem"] },
    status: { type: "string", enum: ["draft", "published", "archived"] },
    thumbnailUrl: nullable({ type: "string", format: "uri" }),
    description: nullable({ type: "string" }),
    authors: array({ type: "string" }),
    metadata,
    sources: array(ref("MapSourceRequest")),
  }, ["gameId", "slug", "name", "type"]),
  MapSummary: object({
    id,
    slug,
    name: { type: "string" },
    type: { type: "string", enum: ["official", "custom", "uem"] },
  }, ["id", "slug", "name"]),
  MapCollection: object({
    search: nullable({ type: "string" }),
    game: nullable({ type: "string" }),
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    hasMore: { type: "boolean" },
    entries: array(object({
      id,
      gameId: id,
      slug,
      name: { type: "string" },
      type: { type: "string", enum: ["official", "custom", "uem"] },
      status: { type: "string", enum: ["draft", "published", "archived"] },
      game: ref("GameSummary"),
    }, ["id", "gameId", "slug", "name", "type", "status", "game"])),
  }, ["search", "game", "page", "pageSize", "hasMore", "entries"]),
  MapUpdateRequest: object({
    name: { type: "string", minLength: 1 },
    status: { type: "string", enum: ["draft", "published", "archived"] },
    thumbnailUrl: nullable({ type: "string", format: "uri" }),
    description: nullable({ type: "string" }),
    authors: array({ type: "string" }),
    metadata,
    sources: array(ref("MapSourceRequest")),
  }),
  MapStatusRequest: object({
    status: { type: "string", enum: ["draft", "published", "archived"] },
  }, ["status"]),
  PaginatedMaps: object({
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    entries: array(ref("Map")),
  }, ["page", "pageSize", "entries"]),
  MapPreviewRequest: object({ url: { type: "string", format: "uri" } }, ["url"]),
  MapImportPreview: object({
    source: { type: "string", enum: ["steam", "ugx", "manual", "other"] },
    sourceUrl: { type: "string", format: "uri" },
    externalId: nullable({ type: "string" }),
    confidence: { type: "string", enum: ["low", "medium", "high"] },
    suggested: metadata,
  }, ["source", "sourceUrl", "externalId", "confidence"]),
  Category: object({
    id,
    slug,
    name: { type: "string" },
    scoreType: { type: "string", enum: ["round", "time", "kills", "points", "custom"] },
    rankingDirection: { type: "string", enum: ["higher_is_better", "lower_is_better"] },
    rules: metadata,
  }, ["id", "slug", "name", "scoreType", "rankingDirection", "rules"]),
  CategoryForMap: object({
    id,
    slug,
    name: { type: "string" },
    scoreType: { type: "string" },
    rankingDirection: { type: "string" },
    rules: metadata,
    assignmentId: id,
    gameId: id,
    mapId: nullable(id),
    globalRules: metadata,
    specificRules: metadata,
  }, [
    "id",
    "slug",
    "name",
    "scoreType",
    "rankingDirection",
    "assignmentId",
    "globalRules",
    "specificRules",
  ]),
  CategorySummary: object({
    id,
    slug,
    name: { type: "string" },
    scoreType: { type: "string" },
    rankingDirection: { type: "string" },
  }, ["id", "slug", "name"]),
  CategorySummaryList: array(ref("CategorySummary")),
  CategoryDefinitionList: array(ref("Category")),
  CategoryList: array(ref("CategoryForMap")),
  CategoryCreateRequest: object({
    slug,
    name: { type: "string", minLength: 1 },
    scoreType: { type: "string", enum: ["round", "time", "kills", "points", "custom"] },
    rankingDirection: { type: "string", enum: ["higher_is_better", "lower_is_better"] },
    rules: metadata,
  }, ["slug", "name", "scoreType", "rankingDirection"]),
  CategoryUpdateRequest: object({
    name: { type: "string", minLength: 1 },
    rules: metadata,
  }),
  CategoryAssignment: object({
    id,
    categoryId: id,
    gameId: id,
    mapId: nullable(id),
    specificRules: metadata,
    createdAt: { type: "string", format: "date-time" },
    category: ref("Category"),
  }, ["id", "categoryId", "gameId", "mapId", "specificRules"]),
  CategoryAssignmentCollection: object({
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    hasMore: { type: "boolean" },
    entries: array(object({
      id,
      categoryId: id,
      gameId: id,
      mapId: nullable(id),
      specificRules: metadata,
      createdAt: { type: "string", format: "date-time" },
      category: ref("Category"),
      game: ref("GameSummary"),
      map: nullable(ref("MapSummary")),
    }, [
      "id",
      "categoryId",
      "gameId",
      "mapId",
      "specificRules",
      "createdAt",
      "category",
      "game",
      "map",
    ])),
  }, ["page", "pageSize", "hasMore", "entries"]),
  CategoryAssignmentCreateRequest: object({
    categoryId: id,
    gameId: id,
    mapId: nullable(id),
    specificRules: metadata,
  }, ["categoryId", "gameId"]),
  CategoryAssignmentUpdateRequest: object({ specificRules: metadata }, ["specificRules"]),
  Mod: object({
    id,
    gameId: id,
    slug,
    name: { type: "string" },
  }, ["id", "gameId", "slug", "name"]),
  ModList: array(ref("Mod")),
  ModCreateRequest: object({
    gameId: id,
    slug,
    name: { type: "string", minLength: 1 },
  }, ["gameId", "slug", "name"]),
  ModUpdateRequest: object({ name: { type: "string", minLength: 1 } }, ["name"]),
  ProofRequest: object({
    type: {
      type: "string",
      enum: ["demo", "input_log", "event_log", "screenshot", "video", "hash_manifest"],
    },
    sourceUrl: nullable({ type: "string", format: "uri" }),
    storageKey: nullable({ type: "string" }),
    sha256: nullable({ type: "string", pattern: "^[a-fA-F0-9]{64}$" }),
    mimeType: nullable({ type: "string" }),
    formatVersion: { type: "integer", minimum: 1 },
    provider: { type: "string", enum: ["youtube", "twitch", "steam", "direct", "other"] },
    metadata,
  }, ["type"]),
  Proof: object({
    id,
    submissionId: id,
    type: {
      type: "string",
      enum: ["demo", "input_log", "event_log", "screenshot", "video", "hash_manifest"],
    },
    sourceUrl: nullable({ type: "string", format: "uri" }),
    storageKey: nullable({ type: "string" }),
    sha256: nullable({ type: "string" }),
    mimeType: nullable({ type: "string" }),
    formatVersion: { type: "integer", minimum: 1 },
    provider: { type: "string", enum: ["youtube", "twitch", "steam", "direct", "other"] },
    metadata,
  }, ["id", "submissionId", "type", "formatVersion", "provider", "metadata"]),
  SubmissionCreateRequest: object({
    gameId: id,
    mapId: id,
    categoryAssignmentId: id,
    scoreValue: { type: "integer", minimum: 1 },
    runDurationMs: nullable({ type: "integer", minimum: 1 }),
    platform: nullable({ type: "string" }),
    gameVersion: nullable({ type: "string" }),
    mapVersion: nullable({ type: "string" }),
    modId: nullable(id),
    modVersion: nullable({ type: "string" }),
    participantUserIds: array({ type: "string" }),
    proofLevel: {
      type: "string",
      enum: ["manual_video", "client_recorded", "client_recorded_with_inputs", "verified_client_package"],
    },
    proofUrl: nullable({ type: "string", format: "uri" }),
    proofs: array(ref("ProofRequest")),
    metadata,
  }, ["gameId", "mapId", "categoryAssignmentId", "scoreValue", "proofLevel"]),
  SubmissionGroupEntryRequest: object({
    categoryAssignmentId: id,
    scoreValue: { type: "integer", minimum: 1 },
    runDurationMs: nullable({ type: "integer", minimum: 1 }),
    metadata,
  }, ["categoryAssignmentId", "scoreValue"]),
  SubmissionGroupCreateRequest: object({
    gameId: id,
    mapId: id,
    platform: nullable({ type: "string" }),
    gameVersion: nullable({ type: "string" }),
    mapVersion: nullable({ type: "string" }),
    modId: nullable(id),
    modVersion: nullable({ type: "string" }),
    participantUserIds: array({ type: "string" }),
    proofLevel: {
      type: "string",
      enum: ["manual_video", "client_recorded", "client_recorded_with_inputs", "verified_client_package"],
    },
    proofUrl: nullable({ type: "string", format: "uri" }),
    proofs: array(ref("ProofRequest")),
    metadata,
    entries: { type: "array", minItems: 1, maxItems: 5, items: ref("SubmissionGroupEntryRequest") },
  }, ["gameId", "mapId", "proofLevel", "entries"]),
  SubmissionReviewRequest: object({
    status: { type: "string", enum: ["verified", "rejected"] },
    reviewNote: nullable({ type: "string" }),
  }, ["status"]),
  ParticipationInvitationDecisionRequest: object({
    status: { type: "string", enum: ["accepted", "rejected"] },
  }, ["status"]),
  Submission: object({
    id,
    submissionGroupId: nullable({ type: "string", format: "uuid" }),
    userId: { type: "string" },
    competitorKey: { type: "string" },
    gameId: id,
    mapId: id,
    categoryId: id,
    categoryAssignmentId: nullable(id),
    scoreValue: { type: "integer" },
    runDurationMs: nullable({ type: "integer" }),
    platform: nullable({ type: "string" }),
    gameVersion: nullable({ type: "string" }),
    mapVersion: nullable({ type: "string" }),
    modId: nullable(id),
    modVersion: nullable({ type: "string" }),
    status: {
      type: "string",
      enum: ["awaiting_participants", "pending", "verified", "rejected", "cancelled"],
    },
    proofLevel: { type: "string" },
    proofUrl: nullable({ type: "string", format: "uri" }),
    reviewNote: nullable({ type: "string" }),
    rulesSnapshot: metadata,
    metadata,
    submittedAt: { type: "string", format: "date-time" },
    verifiedAt: dateTime,
  }, [
    "id",
    "userId",
    "competitorKey",
    "gameId",
    "mapId",
    "categoryId",
    "scoreValue",
    "status",
    "proofLevel",
  ]),
  SubmissionGroupResponse: object({
    submissionGroupId: { type: "string", format: "uuid" },
    submissions: { type: "array", minItems: 1, maxItems: 5, items: ref("Submission") },
  }, ["submissionGroupId", "submissions"]),
  SubmissionReviewResult: object({
    submission: ref("Submission"),
    recordUpdated: { type: "boolean" },
    leaderboardRecalculated: { type: "boolean" },
  }, ["submission", "recordUpdated"]),
  SubmissionDetail: object({
    submission: ref("Submission"),
    game: ref("GameSummary"),
    map: ref("MapSummary"),
    category: ref("CategorySummary"),
    submitter: ref("UserSummary"),
    points: nullable({ type: "number" }),
    participants: array(object({
      submissionId: id,
      role: { type: "string", enum: ["primary", "teammate"] },
      status: { type: "string", enum: ["pending", "accepted", "rejected"] },
      acceptanceSource: {
        type: "string",
        enum: ["submitter", "clan", "invitation", "imported", "legacy"],
      },
      acceptanceClanId: nullable(id),
      respondedAt: dateTime,
      user: ref("UserSummary"),
    }, ["submissionId", "role", "status", "acceptanceSource", "user"])),
    proofs: array(ref("Proof")),
  }, ["submission", "game", "map", "category", "submitter", "points", "participants", "proofs"]),
  SubmissionPage: object({
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 25 },
    hasMore: { type: "boolean" },
    entries: array(ref("SubmissionDetail")),
  }, ["page", "pageSize", "hasMore", "entries"]),
  ParticipationInvitation: object({
    id,
    submissionGroupId: { type: "string", format: "uuid" },
    inviteeUserId: { type: "string" },
    invitedBy: nullable({ type: "string" }),
    status: { type: "string", enum: ["pending", "accepted", "rejected", "revoked", "expired"] },
    expiresAt: { type: "string", format: "date-time" },
    respondedAt: dateTime,
    createdAt: { type: "string", format: "date-time" },
  }, ["id", "submissionGroupId", "inviteeUserId", "status", "expiresAt", "createdAt"]),
  ParticipationGroupParticipant: object({
    submissionId: id,
    userId: { type: "string" },
    role: { type: "string", enum: ["primary", "teammate"] },
    status: { type: "string", enum: ["pending", "accepted", "rejected"] },
    acceptanceSource: {
      type: "string",
      enum: ["submitter", "clan", "invitation", "imported", "legacy"],
    },
    acceptanceClanId: nullable(id),
    respondedAt: dateTime,
  }, ["submissionId", "userId", "role", "status", "acceptanceSource"]),
  ParticipationGroup: object({
    submissionGroupId: { type: "string", format: "uuid" },
    submissions: array(ref("Submission")),
    participants: array(ref("ParticipationGroupParticipant")),
  }, ["submissionGroupId", "submissions", "participants"]),
  ParticipationInvitationList: array(object({
    invitation: ref("ParticipationInvitation"),
    submitter: nullable(ref("UserSummary")),
    group: ref("ParticipationGroup"),
  }, ["invitation", "submitter", "group"])),
  MapLeaderboard: object({
    category: ref("CategoryForMap"),
    pool: { type: "number" },
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    hasMore: { type: "boolean" },
    entries: array(object({
      rank: { type: "integer", minimum: 1 },
      submission: object({
        id,
        scoreValue: { type: "integer" },
        runDurationMs: nullable({ type: "integer" }),
        proofLevel: { type: "string" },
        proofUrl: nullable({ type: "string", format: "uri" }),
        submittedAt: { type: "string", format: "date-time" },
      }, ["id", "scoreValue", "runDurationMs", "proofLevel", "submittedAt"]),
      userId: { type: "string" },
      user: ref("UserSummary"),
      scoreValue: { type: "integer" },
      proofLevel: { type: "string" },
      points: { type: "number" },
      pointFormulaVersion: { type: "string" },
      pointBreakdown: object({
        pool: { type: "number" },
        wrProximity: { type: "number" },
        rankFactor: { type: "number" },
        podiumBonus: { type: "number" },
      }, ["pool", "wrProximity", "rankFactor", "podiumBonus"]),
      participants: array(object({
        user: ref("UserSummary"),
        points: { type: "number" },
      }, ["user", "points"])),
    }, [
      "rank",
      "submission",
      "userId",
      "user",
      "scoreValue",
      "proofLevel",
      "points",
      "pointFormulaVersion",
    ])),
  }, [
    "category",
    "pool",
    "page",
    "pageSize",
    "totalEntries",
    "totalPages",
    "hasMore",
    "entries",
  ]),
  PerformanceLeaderboard: object({
    filters: object({
      categories: array({ type: "string" }),
      game: { type: "string" },
      mapsStatus: { type: "string", enum: ["official", "community"] },
      scope: { type: "string", enum: ["world", "following", "friends"] },
    }, ["categories", "scope"]),
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    totalEntries: { type: "integer", minimum: 0 },
    totalPages: { type: "integer", minimum: 0 },
    hasMore: { type: "boolean" },
    entries: array(object({
      rank: { type: "integer", minimum: 1 },
      user: object({
        id: { type: "string" },
        name: { type: "string" },
        image: nullable({ type: "string", format: "uri" }),
        performancePoints: { type: "number" },
      }, ["id", "name", "image", "performancePoints"]),
      recordCount: { type: "integer", minimum: 0 },
    }, ["rank", "user", "recordCount"])),
  }, ["filters", "page", "pageSize", "totalEntries", "totalPages", "hasMore", "entries"]),
  AchievementLeaderboard: object({
    filters: object({
      country: nullable({ type: "string", pattern: "^[A-Z]{2}$" }),
    }, ["country"]),
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    totalEntries: { type: "integer", minimum: 0 },
    totalPages: { type: "integer", minimum: 0 },
    hasMore: { type: "boolean" },
    entries: array(object({
      rank: { type: "integer", minimum: 1 },
      user: object({
        id: { type: "string" },
        name: { type: "string" },
        image: nullable({ type: "string", format: "uri" }),
        performancePoints: { type: "number" },
      }, ["id", "name", "image", "performancePoints"]),
      achievementPoints: { type: "integer", minimum: 1 },
      unlockedCount: { type: "integer", minimum: 1 },
    }, ["rank", "user", "achievementPoints", "unlockedCount"])),
  }, ["filters", "page", "pageSize", "totalEntries", "totalPages", "hasMore", "entries"]),
  HighestPointRecords: object({
    limit: { type: "integer", const: 50 },
    entries: array(object({
      rank: { type: "integer", minimum: 1, maximum: 50 },
      submissionId: id,
      isWorldRecord: { type: "boolean" },
      points: { type: "number" },
      scoreValue: { type: "number" },
      runDurationMs: nullable({ type: "integer", minimum: 0 }),
      playerCount: { type: "integer", enum: [1, 2, 3, 4] },
      verifiedAt: dateTime,
      game: ref("GameSummary"),
      map: ref("MapSummary"),
      category: ref("CategorySummary"),
      participants: array(object({
        role: { type: "string", enum: ["primary", "teammate"] },
        user: ref("UserSummary"),
      }, ["role", "user"])),
    }, [
      "rank",
      "submissionId",
      "isWorldRecord",
      "points",
      "scoreValue",
      "runDurationMs",
      "playerCount",
      "verifiedAt",
      "game",
      "map",
      "category",
      "participants",
    ])),
  }, ["limit", "entries"]),
  WeeklyPointRecords: {
    allOf: [
      ref("HighestPointRecords"),
      object({ startsAt: dateTime, endsAt: dateTime }, ["startsAt", "endsAt"]),
    ],
  },
  MediaUploadResponse: object({
    kind: { type: "string", enum: ["avatar", "profile-background", "clan-logo", "clan-background"] },
    url: { type: "string" },
  }, ["kind", "url"]),
  HighestAverageLeaderboard: object({
    limit: { type: "integer", const: 50 },
    entries: array(object({
      rank: { type: "integer", minimum: 1, maximum: 50 },
      user: ref("UserSummary"),
      recordCount: { type: "integer", minimum: 5 },
      averagePoints: { type: "number", minimum: 0 },
    }, ["rank", "user", "recordCount", "averagePoints"])),
  }, ["limit", "entries"]),
  ClanLeaderboardRun: object({
    submissionId: id,
    points: { type: "number" },
    playerCount: { type: "integer", enum: [1, 2, 3, 4] },
    verifiedAt: dateTime,
  }, ["submissionId", "points", "playerCount", "verifiedAt"]),
  ClanLeaderboard: object({
    rules: object({
      maxCountedRuns: { type: "integer", const: 20 },
      membership: { type: "string", const: "current" },
      coopRunAttribution: { type: "string", const: "every_represented_clan" },
      duplicatePolicy: { type: "string", const: "once_per_clan" },
    }, ["maxCountedRuns", "membership", "coopRunAttribution", "duplicatePolicy"]),
    filters: object({
      categories: array({ type: "string" }),
      game: nullable({ type: "string" }),
      mapsStatus: nullable({ type: "string", enum: ["official", "community"] }),
      playerCount: nullable({ type: "integer", enum: [1, 2, 3, 4] }),
    }, ["categories", "game", "mapsStatus", "playerCount"]),
    page: { type: "integer", minimum: 0 },
    pageSize: { type: "integer", const: 50 },
    hasMore: { type: "boolean" },
    entries: array(object({
      rank: { type: "integer", minimum: 1 },
      clan: object({
        id,
        slug,
        name: { type: "string" },
        memberCount: { type: "integer", minimum: 1 },
      }, ["id", "slug", "name", "memberCount"]),
      score: { type: "number" },
      eligibleRunCount: { type: "integer", minimum: 1 },
      countedRunCount: { type: "integer", minimum: 1, maximum: 20 },
      countedRuns: array(ref("ClanLeaderboardRun")),
    }, ["rank", "clan", "score", "eligibleRunCount", "countedRunCount", "countedRuns"])),
  }, ["rules", "filters", "page", "pageSize", "hasMore", "entries"]),
  ComparisonRecentRun: object({
    submissionId: id,
    scoreValue: { type: "integer" },
    runDurationMs: nullable({ type: "integer" }),
    playerCount: { type: "integer", minimum: 1 },
    verifiedAt: dateTime,
    map: ref("MapSummary"),
    category: ref("CategorySummary"),
  }, ["submissionId", "scoreValue", "playerCount", "verifiedAt", "map", "category"]),
  ComparisonSide: object({
    user: object({
      id: { type: "string" },
      name: { type: "string" },
      image: nullable({ type: "string", format: "uri" }),
      performancePoints: { type: "number" },
    }, ["id", "name", "image", "performancePoints"]),
    globalRank: { type: "integer", minimum: 1 },
    recordCount: { type: "integer", minimum: 0 },
    recentRuns: array(ref("ComparisonRecentRun")),
  }, ["user", "globalRank", "recordCount", "recentRuns"]),
  ComparisonRecord: object({
    submissionId: id,
    scoreValue: { type: "integer" },
    runDurationMs: nullable({ type: "integer" }),
    points: { type: "number" },
    verifiedAt: dateTime,
  }, ["submissionId", "scoreValue", "points", "verifiedAt"]),
  ProfileComparison: object({
    left: ref("ComparisonSide"),
    right: ref("ComparisonSide"),
    friendship: object({
      leftFollowsRight: { type: "boolean" },
      rightFollowsLeft: { type: "boolean" },
      mutual: { type: "boolean" },
    }, ["leftFollowsRight", "rightFollowsLeft", "mutual"]),
    headToHead: object({
      leftWins: { type: "integer", minimum: 0 },
      rightWins: { type: "integer", minimum: 0 },
      ties: { type: "integer", minimum: 0 },
      commonMapCount: { type: "integer", minimum: 0 },
      commonCategoryCount: { type: "integer", minimum: 0 },
    }, ["leftWins", "rightWins", "ties", "commonMapCount", "commonCategoryCount"]),
    commonBoards: array(object({
      boardKey: { type: "string" },
      game: ref("GameSummary"),
      map: ref("MapSummary"),
      category: object({
        id,
        slug,
        name: { type: "string" },
        scoreType: { type: "string" },
        rankingDirection: { type: "string", enum: ["higher_is_better", "lower_is_better"] },
      }, ["id", "slug", "name", "scoreType", "rankingDirection"]),
      categoryAssignmentId: nullable(id),
      playerCount: { type: "integer", minimum: 1 },
      winnerUserId: nullable({ type: "string" }),
      left: ref("ComparisonRecord"),
      right: ref("ComparisonRecord"),
    }, ["boardKey", "game", "map", "category", "playerCount", "winnerUserId", "left", "right"])),
    sharedTeams: array({ type: "string", pattern: "^team:" }),
  }, ["left", "right", "friendship", "headToHead", "commonBoards", "sharedTeams"]),
  UserPoints: object({
    user: ref("PerformanceUser"),
    totalPoints: { type: "number" },
    records: array(object({
      submissionId: id,
      points: { type: "number" },
    }, ["submissionId", "points"])),
  }, ["user", "totalPoints", "records"]),
  UserProfileLeaderboard: object({
    user: ref("PerformanceUser"),
    records: array(object({
      submissionId: id,
      points: { type: "number" },
      scoreValue: { type: "integer" },
      runDurationMs: nullable({ type: "integer" }),
      proofLevel: { type: "string" },
      verifiedAt: dateTime,
      game: ref("GameSummary"),
      map: ref("MapSummary"),
      category: ref("CategorySummary"),
    }, ["submissionId", "points", "scoreValue", "proofLevel", "game", "map", "category"])),
    history: object({
      page: { type: "integer" },
      pageSize: { type: "integer", const: 10 },
      maxPages: { type: "integer", const: 5 },
      hasMore: { type: "boolean" },
      entries: array(object({
        submissionId: id,
        scoreValue: { type: "integer" },
        runDurationMs: nullable({ type: "integer" }),
        proofLevel: { type: "string" },
        submittedAt: { type: "string", format: "date-time" },
        verifiedAt: dateTime,
        isBestRecord: { type: "boolean" },
        game: ref("GameSummary"),
        map: ref("MapSummary"),
        category: ref("CategorySummary"),
      }, [
        "submissionId",
        "scoreValue",
        "proofLevel",
        "submittedAt",
        "isBestRecord",
        "game",
        "map",
        "category",
      ])),
    }, ["page", "pageSize", "maxPages", "hasMore", "entries"]),
  }, ["user", "records", "history"]),
} as const;
